config/routes.rb
Rails.application.routes.draw do
  resources :enrollments
  resources :participants
  resources :coordinators
  resources :registries
  resources :reports
  get 'download_csv', to: 'reports#download_csv'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "homes#index"
end

app/models/coordinator.rb
class Coordinator < ApplicationRecord
  validates :email, presence: true
  validates :email, uniqueness: true
  has_many :coordinator_registries
  has_many :registries, through: :coordinator_registries
  has_many :enrollments
  has_many :participants, through: :enrollments
end

app/controllers/coordinators_controller.rb
class CoordinatorsController < ApplicationController
  before_action :set_coordinator, only: %i[ show edit update destroy ]

  # GET /coordinators or /coordinators.json
  def index
    @coordinators = Coordinator.all
  end

  # GET /coordinators/1 or /coordinators/1.json
  def show
  end

  # GET /coordinators/new
  def new
    @coordinator = Coordinator.new
  end

  # GET /coordinators/1/edit
  def edit
  end

  # POST /coordinators or /coordinators.json
  def create
    @coordinator = Coordinator.new(coordinator_params)

    respond_to do |format|
      if @coordinator.save
        format.html { redirect_to coordinator_url(@coordinator), notice: "Coordinator was successfully created." }
        format.json { render :show, status: :created, location: @coordinator }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @coordinator.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /coordinators/1 or /coordinators/1.json
  def update
    respond_to do |format|
      if @coordinator.update(coordinator_params)
        format.html { redirect_to coordinator_url(@coordinator), notice: "Coordinator was successfully updated." }
        format.json { render :show, status: :ok, location: @coordinator }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @coordinator.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /coordinators/1 or /coordinators/1.json
  def destroy
    @coordinator.destroy

    respond_to do |format|
      format.html { redirect_to coordinators_url, notice: "Coordinator was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_coordinator
      @coordinator = Coordinator.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def coordinator_params
      params.require(:coordinator).permit(:email, :name, :phone_number, registry_ids: [])
    end
end

app/helpers/coordinators_helper.rb
module CoordinatorsHelper
end

app/views/coordinators/_coordinator.html.erb
<div id="<%= dom_id coordinator %>">
  <p>
    <strong>Email:</strong>
    <%= coordinator.email %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= coordinator.name %>
  </p>

  <p>
    <strong>Phone number:</strong>
    <%= coordinator.phone_number %>
  </p>

  <p>

  <strong>Registries</strong>
    <%= @coordinator.registries.map {|r| "#{r.name} #{r.location}" }.join(",") %>
  </p>

</div>

app/views/coordinators/_form.html.erb
<%= form_with(model: coordinator) do |form| %>
  <% if coordinator.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(coordinator.errors.count, "error") %> prohibited this coordinator from being saved:</h2>

      <ul>
        <% coordinator.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :phone_number, style: "display: block" %>
    <%= form.text_field :phone_number %>
  </div>

  <div>
      <%= form.label :registry %>
      <%= form.select :registry_ids, Registry.all.collect { |r| [ r.name, r.id ] },{},{ multiple: true} %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/coordinators/edit.html.erb
<h1>Editing coordinator</h1>

<%= render "form", coordinator: @coordinator %>

<br>

<div>
  <%= link_to "Show this coordinator", @coordinator %> |
  <%= link_to "Back to coordinators", coordinators_path %>
</div>

app/views/coordinators/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Coordinators</h1>


<table class="table">
  <thead>
    <tr>
      <th>Email</th>
      <th>Name:</th>
      <th>Phone Number:</th>
      <th></th>
    </tr>


  </thead>
   <tbody>
      <% @coordinators.each do |coordinator| %>
    <tr>
      <td><%= coordinator.email %></td>
      <td><%= coordinator.name %></td>
      <td><%= coordinator.phone_number %></td>
      <td><%= link_to "view", coordinator %></td>
    </tr>
      <% end %>

  </tbody>

</table>

<%= link_to "New coordinator", new_coordinator_path %>

app/views/coordinators/new.html.erb
<h1>New coordinator</h1>

<%= render "form", coordinator: @coordinator %>

<br>

<div>
  <%= link_to "Back to coordinators", coordinators_path %>
</div>

app/views/coordinators/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @coordinator %>

<div>
  <%= link_to "Edit this coordinator", edit_coordinator_path(@coordinator) %> |
  <%= link_to "Back to coordinators", coordinators_path %>

  <%= button_to "Destroy this coordinator", @coordinator, method: :delete %>
</div>