config/routes.rb
Rails.application.routes.draw do
  resources :enrollments
  resources :participants
  resources :coordinators
  resources :registries
  resources :reports
  get 'download_csv', to: 'reports#download_csv'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "homes#index"
end

app/models/participant.rb
class Participant < ApplicationRecord
  validates :name, :gender, presence: true
  enum :gender, { male: 0, female: 1 }
  has_many :registries , -> { distinct }, through: :enrollments
  has_many :enrollments
end
# Participant.where("strftime('%Y', date_of_birth) = ?", 1993.to_s)
# Participant.joins(:enrollments).where(gender:"male", enrollments: {coordinator_id: Coordinator.find_by(email:"manish@gmail.com").id}).distinct.count

app/controllers/participants_controller.rb
class ParticipantsController < ApplicationController
  before_action :set_participant, only: %i[ show edit update destroy ]

  # GET /participants or /participants.json
  def index
    @participants = Participant.all
  end

  # GET /participants/1 or /participants/1.json
  def show
  end

  # GET /participants/new
  def new
    @participant = Participant.new
  end

  # GET /participants/1/edit
  def edit
  end

  # POST /participants or /participants.json
  def create
    @participant = Participant.new(participant_params)

    respond_to do |format|
      if @participant.save
        format.html { redirect_to participant_url(@participant), notice: "Participant was successfully created." }
        format.json { render :show, status: :created, location: @participant }

      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @participant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /participants/1 or /participants/1.json
  def update
    respond_to do |format|
      if @participant.update(participant_params)
        format.html { redirect_to participant_url(@participant), notice: "Participant was successfully updated." }
        format.json { render :show, status: :ok, location: @participant }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @participant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /participants/1 or /participants/1.json
  def destroy
    @participant.destroy

    respond_to do |format|
      format.html { redirect_to participants_url, notice: "Participant was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_participant
      @participant = Participant.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def participant_params
      params.require(:participant).permit(:name, :gender, :date_of_birth)
    end
end

app/helpers/participants_helper.rb
module ParticipantsHelper
end

app/views/participants/_form.html.erb
<%= form_with(model: participant) do |form| %>
  <% if participant.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(participant.errors.count, "error") %> prohibited this participant from being saved:</h2>

      <ul>
        <% participant.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :gender, style: "display: block" %>
    <%= form.select :gender, Participant.genders.keys %>
  </div>

  <div>
    <%= form.label :date_of_birth, style: "display: block" %>
    <%= form.date_field :date_of_birth %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/participants/_participant.html.erb
<div id="<%= dom_id participant %>">
  <p>
    <strong>Name:</strong>
    <%= participant.name %>
  </p>

  <p>
    <strong>Gender:</strong>
    <%= participant.gender %>
  </p>

  <p>
    <strong>Date of birth:</strong>
    <%= participant.date_of_birth %>
  </p>

</div>

app/views/participants/edit.html.erb
<h1>Editing participant</h1>

<%= render "form", participant: @participant %>

<br>

<div>
  <%= link_to "Show this participant", @participant %> |
  <%= link_to "Back to participants", participants_path %>
</div>

app/views/participants/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Participants</h1>


<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Gender:</th>
      <th>Date of Birth:</th>
      <th></th>
    </tr>


  </thead>
   <tbody>
      <% @participants.each do |participant| %>
    <tr>
      <td><%= participant.name %></td>
      <td><%= participant.gender %></td>
      <td><%= participant.date_of_birth %></td>
      <td><%= link_to "view", participant %></td>
    </tr>
      <% end %>

  </tbody>

</table>

<%= link_to "New participant", new_participant_path %>

app/views/participants/new.html.erb
<h1>New participant</h1>

<%= render "form", participant: @participant %>

<br>

<div>
  <%= link_to "Back to participants", participants_path %>
</div>

app/views/participants/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @participant %>

<div>
  <%= link_to "Edit this participant", edit_participant_path(@participant) %> |
  <%= link_to "Back to participants", participants_path %>

  <%= button_to "Destroy this participant", @participant, method: :delete %>
</div>