config/routes.rb
Rails.application.routes.draw do
  resources :enrollments
  resources :participants
  resources :coordinators
  resources :registries
  resources :reports
  get 'download_csv', to: 'reports#download_csv'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "homes#index"
end

app/models/registry.rb
class Registry < ApplicationRecord
  validates :name, :location, presence: true
  validates :name, uniqueness: { scope: :location }

  enum :state, { closed: 0, open: 1 }
  has_many :coordinator_registries
  has_many :coordinators, through: :coordinator_registries
  has_many :enrollments

end

app/controllers/registries_controller.rb
class RegistriesController < ApplicationController
  before_action :set_registry, only: %i[ show edit update destroy ]

  # GET /registries or /registries.json
  def index
    @registries = Registry.all
  end

  # GET /registries/1 or /registries/1.json
  def show
  end

  # GET /registries/new
  def new
    @registry = Registry.new
  end

  # GET /registries/1/edit
  def edit
  end

  # POST /registries or /registries.json
  def create
    @registry = Registry.new(registry_params)

    respond_to do |format|
      if @registry.save
        format.html { redirect_to registry_url(@registry), notice: "Registry was successfully created." }
        format.json { render :show, status: :created, location: @registry }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @registry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /registries/1 or /registries/1.json
  def update
    respond_to do |format|
      if @registry.update(registry_params)
        format.html { redirect_to registry_url(@registry), notice: "Registry was successfully updated." }
        format.json { render :show, status: :ok, location: @registry }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @registry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /registries/1 or /registries/1.json
  def destroy
    @registry.destroy

    respond_to do |format|
      format.html { redirect_to registries_url, notice: "Registry was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_registry
      @registry = Registry.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def registry_params
      params.require(:registry).permit(:name, :location, :state, coordinator_ids: [])
    end
end

app/helpers/registries_helper.rb
module RegistriesHelper
end

app/views/registries/_form.html.erb
<%= form_with(model: registry) do |form| %>
  <% if registry.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(registry.errors.count, "error") %> prohibited this registry from being saved:</h2>

      <ul>
        <% registry.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :location, style: "display: block" %>
    <%= form.text_area :location %>
  </div>

  <div>
    <%= form.label :state, style: "display: block" %>
    <%= form.select :state, Registry.states.keys %>
  </div>

  <div>
      <%= form.label :coordinators %>
      <%= form.select :coordinator_ids, Coordinator.all.collect { |c| [ c.email, c.id ] },{},{ multiple: true} %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/registries/_registry.html.erb
<div id="<%= dom_id registry %>">
  <p>
    <strong>Name:</strong>
    <%= registry.name %>
  </p>

  <p>
    <strong>Location:</strong>
    <%= registry.location %>
  </p>

  <p>
    <strong>State:</strong>
    <%= registry.state %>
  </p>

  <p>

  <strong>Coordinators</strong>
    <%= @registry.coordinators.map {|c| "#{c.email}" }.join(",") %>
  </p>

</div>

app/views/registries/edit.html.erb
<h1>Editing registry</h1>

<%= render "form", registry: @registry %>

<br>

<div>
  <%= link_to "Show this registry", @registry %> |
  <%= link_to "Back to registries", registries_path %>
</div>

app/views/registries/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Registries</h1>


<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Location:</th>
      <th>State:</th>
      <th></th>
    </tr>


  </thead>
   <tbody>
      <% @registries.each do |registry| %>
    <tr>
      <td><%= registry.name %></td>
      <td><%= registry.location %></td>
      <td><%= registry.state %></td>
      <td><%= link_to "view", registry %></td>
    </tr>
      <% end %>

  </tbody>

</table>

<%= link_to "New registry", new_registry_path %>

app/views/registries/new.html.erb
<h1>New registry</h1>

<%= render "form", registry: @registry %>

<br>

<div>
  <%= link_to "Back to registries", registries_path %>
</div>

app/views/registries/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @registry %>

<div>
  <%= link_to "Edit this registry", edit_registry_path(@registry) %> |
  <%= link_to "Back to registries", registries_path %>

  <%= button_to "Destroy this registry", @registry, method: :delete %>
</div>