config/routes.rb
Rails.application.routes.draw do
  resources :enrollments
  resources :participants
  resources :coordinators
  resources :registries
  resources :reports
  get 'download_csv', to: 'reports#download_csv'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "homes#index"
end

app/models/enrollment.rb
class Enrollment < ApplicationRecord
  enum :method_of_contact, { phone: 0, email: 1 }
  belongs_to :participant
  belongs_to :registry
  belongs_to :coordinator
  validates :participant, uniqueness: { scope: :registry }
  validates_with EnrollmentValidator


end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
  before_action :set_enrollment, only: %i[ show edit update destroy ]

  # GET /enrollments or /enrollments.json
  def index
    @enrollments = Enrollment.all
  end

  # GET /enrollments/1 or /enrollments/1.json
  def show
  end

  # GET /enrollments/new
  def new
    @enrollment = Enrollment.new
  end

  # GET /enrollments/1/edit
  def edit
  end

  # POST /enrollments or /enrollments.json
  def create
    @enrollment = Enrollment.new(enrollment_params)

    respond_to do |format|
      if @enrollment.save
        format.html { redirect_to enrollment_url(@enrollment), notice: "Enrollment was successfully created." }
        format.json { render :show, status: :created, location: @enrollment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @enrollment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /enrollments/1 or /enrollments/1.json
  def update
    respond_to do |format|
      if @enrollment.update(enrollment_params)
        format.html { redirect_to enrollment_url(@enrollment), notice: "Enrollment was successfully updated." }
        format.json { render :show, status: :ok, location: @enrollment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @enrollment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /enrollments/1 or /enrollments/1.json
  def destroy
    @enrollment.destroy

    respond_to do |format|
      format.html { redirect_to enrollments_url, notice: "Enrollment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_enrollment
      @enrollment = Enrollment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def enrollment_params
      params.require(:enrollment).permit(:date_of_enrollment, :method_of_contact, :remarks, :participant_id, :registry_id, :coordinator_id)
    end
end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/views/enrollments/_enrollment.html.erb
<div id="<%= dom_id enrollment %>">
  <p>
    <strong>Participant Name:</strong>
    <%= enrollment.participant.name %>
  </p>
  <p>
    <strong>Registry:</strong>
    <%= enrollment.registry.name + " "+ enrollment.registry.location%>
  </p>
  <p>
    <strong>Date of enrollment:</strong>
    <%= enrollment.date_of_enrollment %>
  </p>

  <p>
    <strong>Method of contact:</strong>
    <%= enrollment.method_of_contact %>
  </p>

  <p>
    <strong>Remarks:</strong>
    <%= enrollment.remarks %>
  </p>

  <p>
    <strong>Coordinator:</strong>
    <%= enrollment.coordinator.email %>
  </p>

</div>

app/views/enrollments/_form.html.erb
<%= form_with(model: enrollment) do |form| %>
  <% if enrollment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(enrollment.errors.count, "error") %> prohibited this enrollment from being saved:</h2>

      <ul>
        <% enrollment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
      <%= form.label :participant %>
      <%= form.select :participant_id, Participant.all.collect { |r| [ r.name, r.id ] }%>
  </div>

  <div>
      <%= form.label :registry %>
      <%= form.select :registry_id, Registry.where(state:'open').collect { |r| [ r.name, r.id ] }%>
  </div>

  <div>
    <%= form.label :date_of_enrollment, style: "display: block" %>
    <%= form.date_field :date_of_enrollment %>
  </div>

  <div>
    <%= form.label :method_of_contact, style: "display: block" %>
    <%= form.select :method_of_contact, Enrollment.method_of_contacts.keys %>
  </div>

  <div>
    <%= form.label :remarks, style: "display: block" %>
    <%= form.text_field :remarks %>
  </div>

  <div>
      <%= form.label :coordinator %>
      <%= form.select :coordinator_id, Coordinator.all.collect { |c| [ c.email, c.id ] } %>
  </div>


  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/enrollments/edit.html.erb
<h1>Editing enrollment</h1>

<%= render "form", enrollment: @enrollment %>

<br>

<div>
  <%= link_to "Show this enrollment", @enrollment %> |
  <%= link_to "Back to enrollments", enrollments_path %>
</div>

app/views/enrollments/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Enrollments</h1>


<table class="table">
  <thead>
    <tr>
      <th>Participant:</th>
      <th>Registry:</th>
      <th>Date of enrollment</th>
      <th>Method of contact:</th>
      <th>Coordinator:</th>
      <th>Remarks:</th>
      <th></th>
    </tr>


  </thead>
   <tbody>
      <% @enrollments.each do |enrollment| %>
    <tr>
      <td><%= enrollment.participant.name %></td>
      <td><%= enrollment.registry.name %> <%= enrollment.registry.location %></td>
      <td><%= enrollment.date_of_enrollment %></td>
      <td><%= enrollment.method_of_contact %></td>
      <td><%= enrollment.coordinator.email %></td>
      <td><%= enrollment.remarks %></td>
      <td><%= link_to "view", enrollment %></td>
    </tr>
      <% end %>

  </tbody>

</table>

<%= link_to "New enrollment", new_enrollment_path %>

app/views/enrollments/new.html.erb
<h1>New enrollment</h1>

<%= render "form", enrollment: @enrollment %>

<br>

<div>
  <%= link_to "Back to enrollments", enrollments_path %>
</div>

app/views/enrollments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @enrollment %>

<div>
  <%= link_to "Edit this enrollment", edit_enrollment_path(@enrollment) %> |
  <%= link_to "Back to enrollments", enrollments_path %>

  <%= button_to "Destroy this enrollment", @enrollment, method: :delete %>
</div>